### ISSUE TITLE
RFE:  Complete the template

### ISSUE THREAD

**Issue by kfiresmith** [idiv-biodiversity/ansible-role-systemd-journald#2]
Hi again Christian,
Currently I use this non-galaxy role, which is a bit more complete but appears to be abandoned (AFAICT, the sole Ansible dev w/ Stone Payments works elsewhere now):  https://github.com/stone-payments/ansible-journald

As you can see from my PR over there [#2](https://github.com/stone-payments/ansible-journald/pull/2), I'm not having much luck, and also it is not as nice to use that Github based role as it would be to use a Galaxy Role that can be installed and managed using the normal methods.

As such, what do you think about using that role as inspiration to make your role more feature-complete?  I suspect that this role will work just fine with most systemd distros, including Ubuntu 18.04+ and RHEL/CentOS 7+

**Comment by wookietreiber** [comment]
With most, if not all, of my roles, I use the approach to only support (do the work for) the stuff that I need. I don't necessarily have the time to aim for feature-completeness, i.e. doing it myself / on my own. That said, I'm totally fine with someone else opening up PR's for the features / variables they need. So, feel free to open up PR's :smiley:
