### ISSUE TITLE
Package installation task specific to Arch.  Please generalize this.

### ISSUE THREAD

**Issue by kfiresmith** [idiv-biodiversity/ansible-role-systemd-journald#6]
Currently in tasks/main.yaml we see a package installation call for `pacman: systemd`.

IMO since this is a simple package installation operation for a package that is widely uniformly named, we should generalize this out to `ansible.builtin.package: systemd`.

Tested this locally on Ubuntu and works fine as expected.  PR incoming.

**Comment by wookietreiber** [comment]
Thanks for #7!

**Comment by wookietreiber** [comment]
fixed in 984bd02d665fe5d789697391cd73ce43d1a72f91
